[package]
name = "anyhow-error-response"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
axum = "0.6.6"
tokio = { version = "1.25.0", features = ["full"] }
